//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webhoconl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oder()
        {
            this.OderDetails = new HashSet<OderDetail>();
        }
    
        public int Oder_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<System.DateTime> Oder_Date { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Phonenumber { get; set; }
        public Nullable<int> CreditCardNumber { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string BankingName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string name { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderDetail> OderDetails { get; set; }
    }
}
