//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webhoconl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectContent
    {
        public Nullable<int> Subject_ID { get; set; }
        public int SectionId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string VideoLink { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
